export const singleEmployeeExportOptions = {
  employee_details: [
    "employee_details_gender",
    "employee_details_phone",
    "employee_details_email",
    "employee_details_user_id",
    "employee_details_name",
  ],
  social_links: ["social_links_url", "social_links_website"],
  bank_details: [
    "bank_details_account_number",
    "bank_details_account_name",
    "bank_details_sort_code",
    "bank_details_name",
  ],
  notes: ["notes_description", "notes_title"],
  contact_details: [
    "contact_details_mobile_tel_number",
    "contact_details_evening_time_tel_number",
    "contact_details_day_time_tel_number",
    "contact_details_postcode",
    "contact_details_address",
    "contact_details_relationship",
    "contact_details_last_name",
    "contact_details_first_name",
  ],
  address_details: [
    "address_details_postcode",
    "address_details_country",
    "address_details_city",
    "address_details_address",
  ],
  current_right_to_works: [
    "current_right_to_works_right_to_work_docs",
    "current_right_to_works_right_to_work_expiry_date",
    "current_right_to_works_right_to_work_check_date",
    "current_right_to_works_right_to_work_code",
  ],
  current_visa_details: [
    "current_visa_details_place_of_issue",
    "current_visa_details_brp_number",
    "current_visa_details_expiry_date",
    "current_visa_details_issue_date",
  ],
  current_passport_details: [
    "current_passport_details_place_of_issue",
    "current_passport_details_passport_number",
    "current_passport_details_expiry_date",
    "current_passport_details_issue_date",
  ],
  current_cos_details: [
    "current_cos_details_note",
    "current_cos_details_current_certificate_status",
    "current_cos_details_certificate_number",
    "current_cos_details_expiry_date",
    "current_cos_details_date_assigned",
  ],
  job_history: [
    "job_history_country",
    "job_history_supervisor",
    "job_history_end_at",
    "job_history_start_on",
    "job_history_company",
    "job_history_job_title",
  ],
  educational_history: [
    "educational_history_achievements",
    "educational_history_start_date",
    "educational_history_major",
    "educational_history_degree",
  ],
  assets: [
    "asset_note",
    "asset_date",
    "asset_type",
    "asset_is_working",
    "asset_serial_number",
    "asset_code",
    "asset_name",
  ],
  documents: ["document_added_by", "document_title"],
  leaves: [
    "total_leave_hours",
    "leave_duration",
    "leave_type",
    "leave_date_time",
  ],
  attendances: [
    "attendance_overtime",
    "attendance_schedule",
    "attendance_break",
    "attendance_end_time",
    "attendance_start_time",
    "attendance_date",
  ],
  leave_allowances: [
    "leave_allowance_availability",
    "leave_allowance_earned",
    "leave_allowance_allowance",
    "leave_allowance_type",
    "leave_allowance_name",
  ],
};
